kind: ReplicationController
apiVersion: v1
metadata:
  name: guestbook
  labels:
    app: guestbook
spec:
  replicas: 3
  selector:
    app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - name: guestbook
        image: 506539650117.dkr.ecr.us-west-1.amazonaws.com/nvermand:latest
        ports:
        - name: http-server
          containerPort: 3000
      imagePullSecrets:
      - name: ecr  
